GET http://localhost:3002/api/persons/

###
GET http://localhost:3002/info/

###
GET http://localhost:3002/api/persons/2

###
GET http://localhost:3002/api/persons/6978b198fd2a0a0daf0a512d

###
GET http://localhost:3002/api/persons/6978b198fd2a0a0daf0a0000

###
GET https://phonebook-9u4u.onrender.com/api/persons/2

###
DELETE http://localhost:3002/api/persons/697a0f966aa8008a778e2b41

###
DELETE https://phonebook-9u4u.onrender.com/api/persons/697a30436167f190b295cae3

###
POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "VSCode testing 3 json",
    "number": 332456254
}

###
POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": " ",
    "number": 332456254
}
